name:                vector-sum-benchmarks
version:             0.1.0.0
github:              "Fuuzetsu/vector-sum-benchmarks"
license:             BSD3
author:              "Mateusz Kowalczyk"
maintainer:          "fuuzetsu@fuuzetsu.co.uk"
copyright:           "2018, Mateusz Kowalczyk"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/Fuuzetsu/vector-sum-benchmarks#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -O2
  dependencies:
  - vector

tests:
  vector-sum-benchmarks-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N -O2
    dependencies:
    - hspec
    - vector
    - vector-sum-benchmarks

benchmarks:
  vector-sum-benchmarks-bench:
    main:                Main.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N -O2
    dependencies:
    - criterion
    - deepseq
    - vector
    - vector-sum-benchmarks

benchmarks:
  vector-sum-benchmarks-alloc:
    main:                Main.hs
    source-dirs:         alloc
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N -O2
    dependencies:
    - deepseq
    - vector
    - vector-sum-benchmarks
    - weigh
